# Generated by Django 4.2 on 2023-04-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название тарифа')),
                ('description', models.TextField(verbose_name='Описание')),
                ('old_price', models.IntegerField(verbose_name='Старая цена')),
                ('new_price', models.IntegerField(verbose_name='Новая цена')),
            ],
        ),
    ]
