# Generated by Django 4.2 on 2023-04-24 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_username', models.CharField(max_length=255, verbose_name='Телеграм юзернейм')),
                ('type', models.CharField(max_length=255, verbose_name='Направление')),
            ],
        ),
        migrations.AddField(
            model_name='tariff',
            name='type',
            field=models.CharField(choices=[('Front-end', 'Front-end'), ('Back-end', 'Back-end'), ('Design', 'Design')], default=3, max_length=50, verbose_name='Тип курса'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Telegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст приветствия')),
                ('group_link', models.URLField(max_length=255, verbose_name='Ссылка на группу')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tariff.mentors', verbose_name='Направление')),
            ],
        ),
    ]
