# Generated by Django 4.2 on 2023-04-24 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0002_mentors_tariff_type_telegram'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mentors',
            new_name='Mentor',
        ),
    ]
