# Generated by Django 4.2 on 2023-04-26 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_username', models.CharField(max_length=255, verbose_name='Телеграм юзернейм')),
                ('type', models.CharField(choices=[('Front-end', 'Front-end'), ('Back-end', 'Back-end'), ('Design', 'Design')], max_length=255, verbose_name='Направление')),
            ],
        ),
        migrations.CreateModel(
            name='Telegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Внимание! при отправке текста пользователю внутри {} скобок пишется его, не забудьте оставить скобки', verbose_name='Текст приветствия')),
                ('group_link', models.URLField(max_length=255, verbose_name='Ссылка на группу')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_app.mentor', verbose_name='Направление')),
            ],
        ),
    ]
