# Generated by Django 4.2 on 2023-04-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegram',
            name='text',
        ),
        migrations.AddField(
            model_name='telegram',
            name='chat_welcome_text',
            field=models.TextField(default=3, help_text='Внимание! при отправке текста пользователю внутри {} скобок пишется его, не забудьте оставить скобки', verbose_name='Текст приветствия в личных сообщениях'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telegram',
            name='group_welcome_text',
            field=models.TextField(default=3, help_text='Внимание! при отправке текста пользователю внутри {} скобок пишется его, не забудьте оставить скобки', verbose_name='Текст приветствия в группе'),
            preserve_default=False,
        ),
    ]
