# Generated by Django 4.2 on 2023-04-27 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0002_remove_telegram_text_telegram_chat_welcome_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegram',
            old_name='group_link',
            new_name='installment_program',
        ),
    ]
