# Generated by Django 4.2 on 2023-04-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0003_rename_group_link_telegram_installment_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegram',
            name='manager_telegram_username',
            field=models.URLField(default=3, max_length=255, verbose_name='Ссылка на телеграм менеджера'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='telegram',
            name='installment_program',
            field=models.TextField(verbose_name='Текст приветствия для программы рассрочки'),
        ),
    ]
