# Generated by Django 4.2 on 2023-04-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0004_telegram_manager_telegram_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Юзернейм')),
                ('name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('user_chat_id', models.IntegerField(verbose_name='ID переписки')),
            ],
            options={
                'verbose_name': 'Пользователь Телеграма',
                'verbose_name_plural': 'Пользователи Телеграма',
            },
        ),
        migrations.AlterModelOptions(
            name='mentor',
            options={'verbose_name': 'Ментор', 'verbose_name_plural': 'Менторы'},
        ),
        migrations.AlterModelOptions(
            name='telegram',
            options={'verbose_name': 'Текст для Телеграма', 'verbose_name_plural': 'Тексты для Телеграма'},
        ),
    ]
