# Generated by Django 4.2 on 2023-05-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0006_rename_telegramusers_telegramuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegram',
            name='manager_telegram_username',
        ),
        migrations.AddField(
            model_name='telegram',
            name='manager_telegram_id',
            field=models.IntegerField(default=1, verbose_name='ID менеджера телеграм'),
            preserve_default=False,
        ),
    ]
