# Generated by Django 4.2 on 2023-05-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0009_telegramgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramgroup',
            name='group_id',
        ),
        migrations.AddField(
            model_name='telegramgroup',
            name='group_link',
            field=models.URLField(default=3, max_length=1000, verbose_name='ID группы телеграма'),
            preserve_default=False,
        ),
    ]
