# Generated by Django 4.2 on 2023-05-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0010_remove_telegramgroup_group_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegram',
            name='chat_welcome_text',
            field=models.TextField(help_text='Внимание! при отправке текста пользователю внутри  скобок пишется его, не забудьте оставить скобки', verbose_name='Текст приветствия в личных сообщениях'),
        ),
    ]
