# Generated by Django 4.2 on 2023-05-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0011_alter_telegram_chat_welcome_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegram',
            name='group_welcome_text',
        ),
        migrations.AddField(
            model_name='telegramgroup',
            name='group_welcome_text',
            field=models.TextField(default=3, help_text='Внимание! при отправке текста пользователю внутри {} скобок пишется его, не забудьте оставить скобки', verbose_name='Текст приветствия в группе'),
            preserve_default=False,
        ),
    ]
