# Generated by Django 4.2 on 2023-05-15 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0020_course_lms_url'),
        ('telegram_app', '0012_remove_telegram_group_welcome_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='type',
        ),
        migrations.AddField(
            model_name='mentor',
            name='direction',
            field=models.ForeignKey(default=2, max_length=255, on_delete=django.db.models.deletion.CASCADE, to='payment_app.tariff', verbose_name='Направление'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telegram',
            name='type',
            field=models.ForeignKey(default=2, max_length=255, on_delete=django.db.models.deletion.CASCADE, to='payment_app.course', verbose_name='Направление'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telegramgroup',
            name='type',
            field=models.ForeignKey(default=2, max_length=255, on_delete=django.db.models.deletion.CASCADE, to='payment_app.course', verbose_name='Направление'),
            preserve_default=False,
        ),
    ]
