# Generated by Django 4.2.1 on 2023-05-18 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0013_remove_mentor_type_mentor_direction_telegram_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramgroup',
            name='type',
        ),
        migrations.DeleteModel(
            name='TelegramUser',
        ),
        migrations.AlterModelOptions(
            name='telegram',
            options={'verbose_name': 'Телеграм группа', 'verbose_name_plural': 'Телеграм группа'},
        ),
        migrations.RemoveField(
            model_name='telegram',
            name='chat_welcome_text',
        ),
        migrations.RemoveField(
            model_name='telegram',
            name='installment_program',
        ),
        migrations.RemoveField(
            model_name='telegram',
            name='manager_telegram_id',
        ),
        migrations.AddField(
            model_name='telegram',
            name='group_link',
            field=models.URLField(default=3, max_length=255, verbose_name='Ссылка на группу'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='telegram',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_app.mentor', verbose_name='Ментор'),
        ),
        migrations.DeleteModel(
            name='TelegramGroup',
        ),
    ]
