# Generated by Django 4.2.1 on 2023-05-18 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0029_alter_payboxsuccesspay_description'),
        ('telegram_app', '0014_remove_telegramgroup_type_delete_telegramuser_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Telegram',
            new_name='TelegramGroup',
        ),
    ]
