# Generated by Django 4.2.1 on 2023-05-18 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0029_alter_payboxsuccesspay_description'),
        ('telegram_app', '0015_rename_telegram_telegramgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='telegram_username',
        ),
        migrations.AddField(
            model_name='mentor',
            name='user_link',
            field=models.CharField(default=3, max_length=255, verbose_name='Ссылка на пользователя телеграм'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='telegramgroup',
            name='type',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='payment_app.course', verbose_name='Курс'),
        ),
    ]
