# Generated by Django 4.2.1 on 2023-05-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0019_contactustelegram_alter_telegrammessage_manager_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactustelegram',
            name='bot_token',
        ),
        migrations.RemoveField(
            model_name='telegrammessage',
            name='bot_token',
        ),
        migrations.AddField(
            model_name='telegramgroup',
            name='text',
            field=models.TextField(default=3, verbose_name='Текст приветствия'),
            preserve_default=False,
        ),
    ]
