# Generated by Django 4.2.1 on 2023-05-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0021_installmenttelegram'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_link', models.URLField(help_text='пример: https://t.me/TEST_BOT', max_length=100, verbose_name='Ссылка на бота')),
            ],
            options={
                'verbose_name': 'Телеграм бот',
                'verbose_name_plural': 'Телеграм бот',
            },
        ),
        migrations.AlterModelOptions(
            name='installmenttelegram',
            options={'verbose_name': 'Программа рассрочки', 'verbose_name_plural': 'Программа рассрочки'},
        ),
        migrations.AlterModelOptions(
            name='telegramgroup',
            options={'verbose_name': 'Сообщение при добавлении в группу', 'verbose_name_plural': 'Сообщение при добавлении в группу'},
        ),
        migrations.AlterModelOptions(
            name='telegrammessage',
            options={'verbose_name': 'Сообщение при добавлении', 'verbose_name_plural': 'Сообщение при добавлении'},
        ),
    ]
