# Generated by Django 4.2.1 on 2023-07-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0024_alter_contactustelegram_manager_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='ID пользователя')),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('country', models.CharField(choices=[('KG', 'Kyrgyzstan'), ('UZ', 'Uzbekistan'), ('KZ', 'Kazakhstan'), ('RU', 'Russia'), ('TJ', 'Tajikistan')], verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Вебинар',
                'verbose_name_plural': 'Вебинары',
            },
        ),
    ]
