# Generated by Django 4.2.1 on 2023-07-28 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0027_remove_telegramuser_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='country',
        ),
    ]
