# Generated by Django 4.2.1 on 2023-07-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0028_remove_telegramuser_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='location',
            field=models.CharField(default=3, max_length=255, verbose_name=''),
            preserve_default=False,
        ),
    ]
