# Generated by Django 4.2.1 on 2023-07-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0029_telegramuser_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Часовой пояс'),
        ),
    ]
