# Generated by Django 4.2.1 on 2023-08-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0030_alter_telegramuser_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAdmin',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Телеграм ID')),
            ],
            options={
                'verbose_name': 'Администратор Telegram',
                'verbose_name_plural': 'Администраторы Telegram',
            },
        ),
    ]
