# Generated by Django 4.2.1 on 2023-08-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0031_telegramadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='phone_number',
            field=models.CharField(default=3, max_length=100, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
