# Generated by Django 4.2.1 on 2023-08-18 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0033_alter_telegramuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='user_id',
            field=models.BigIntegerField(unique=True, verbose_name='ID пользователя'),
        ),
    ]
