# Generated by Django 4.2 on 2023-04-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000, verbose_name='Ссылки с Paybox оплаты')),
                ('type_of', models.CharField(choices=[('Front-end', 'Front-end'), ('Back-end', 'Back-end'), ('Design', 'Design')], max_length=20)),
            ],
        ),
    ]
