# Generated by Django 4.2 on 2023-04-29 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0003_alter_urls_type_of'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Urls',
            new_name='PayboxUrl',
        ),
    ]
