# Generated by Django 4.2 on 2023-05-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0005_alter_payboxurl_type_of'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название курса')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.RenameModel(
            old_name='Tariff',
            new_name='CoursePrompt',
        ),
        migrations.AlterModelOptions(
            name='courseprompt',
            options={'verbose_name': 'Карточка курса', 'verbose_name_plural': 'Карточки курсов'},
        ),
    ]
