# Generated by Django 4.2 on 2023-05-10 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0006_course_rename_tariff_courseprompt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayboxSuccessPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название тарифа')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.DeleteModel(
            name='CoursePrompt',
        ),
        migrations.DeleteModel(
            name='PayboxUrl',
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Карточка курса', 'verbose_name_plural': 'Карточки курсов'},
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default=3, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='new_price',
            field=models.IntegerField(default=3, verbose_name='Новая цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='old_price',
            field=models.IntegerField(default=3, verbose_name='Старая цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='url',
            field=models.URLField(default=3, max_length=1000, verbose_name='Ссылки с Paybox оплаты'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название тарифа'),
        ),
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='payment_app.tariff', verbose_name='Тип курса'),
            preserve_default=False,
        ),
    ]
