# Generated by Django 4.2 on 2023-05-10 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0008_alter_course_options_alter_course_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayboxSuccessPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.IntegerField(verbose_name='ID оплаты')),
                ('amount', models.IntegerField(verbose_name='Цена')),
                ('currency', models.CharField(max_length=3, verbose_name='Валюта')),
                ('description', models.CharField(max_length=100, verbose_name='Описание к оплате')),
                ('payment_date', models.DateField(default=datetime.datetime(2023, 5, 10, 20, 49, 14, 832945), verbose_name='Дата оплаты')),
                ('user_phone', models.CharField(max_length=25, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=255, verbose_name='Почта')),
                ('signature', models.CharField(verbose_name='Подпись продукта')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
            },
        ),
    ]
