# Generated by Django 4.2 on 2023-05-12 09:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0009_payboxsuccesspay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название курса'),
        ),
        migrations.AlterField(
            model_name='payboxsuccesspay',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата оплаты'),
        ),
    ]
