# Generated by Django 4.2 on 2023-05-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0011_alter_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
