# Generated by Django 4.2 on 2023-05-12 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0013_alter_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payboxsuccesspay',
            name='name',
            field=models.CharField(default=3, max_length=255, verbose_name='Название Курса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payboxsuccesspay',
            name='order_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='payment_app.course', verbose_name='ID Курса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payboxsuccesspay',
            name='type',
            field=models.CharField(default=3, max_length=255, verbose_name='Тариф'),
            preserve_default=False,
        ),
    ]
