# Generated by Django 4.2 on 2023-05-12 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0014_payboxsuccesspay_name_payboxsuccesspay_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='url',
        ),
    ]
