# Generated by Django 4.2 on 2023-05-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0016_alter_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payboxsuccesspay',
            name='order_id',
            field=models.IntegerField(verbose_name='ID Курса'),
        ),
    ]
