# Generated by Django 4.2 on 2023-05-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0017_alter_payboxsuccesspay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payboxsuccesspay',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус оплаты'),
        ),
    ]
