# Generated by Django 4.2 on 2023-05-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0018_payboxsuccesspay_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='new_price',
        ),
        migrations.RemoveField(
            model_name='course',
            name='old_price',
        ),
        migrations.AddField(
            model_name='tariff',
            name='description',
            field=models.TextField(default=3, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tariff',
            name='new_price',
            field=models.IntegerField(default=3, verbose_name='Новая цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tariff',
            name='old_price',
            field=models.IntegerField(default=3, verbose_name='Старая цена'),
            preserve_default=False,
        ),
    ]
