# Generated by Django 4.2 on 2023-05-15 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0019_remove_course_description_remove_course_new_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lms_url',
            field=models.URLField(default=2, max_length=1500, verbose_name='Ссылка на курс'),
            preserve_default=False,
        ),
    ]
