# Generated by Django 4.2.1 on 2023-05-15 20:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0020_course_lms_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('telegram_number', models.CharField(max_length=20, verbose_name='Телеграм номер')),
                ('start_date', models.DateField(default=datetime.datetime(2023, 5, 15, 20, 16, 1, 339272, tzinfo=datetime.timezone.utc), verbose_name='Дата начала доступа')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_app.tariff', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Временный доступ',
                'verbose_name_plural': 'Временные доступы',
            },
        ),
    ]
