# Generated by Django 4.2.1 on 2023-05-15 20:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0021_temporaryaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryaccess',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='temporaryaccess',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала доступа'),
        ),
        migrations.AlterField(
            model_name='temporaryaccess',
            name='telegram_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Телеграм номер'),
        ),
    ]
