# Generated by Django 4.2.1 on 2023-05-15 21:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0022_alter_temporaryaccess_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryaccess',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала доступа'),
        ),
    ]
