# Generated by Django 4.2.1 on 2023-05-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0023_alter_temporaryaccess_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryaccess',
            name='temporary_url',
            field=models.URLField(default=3, max_length=1000, verbose_name='Ссылка временного курса'),
            preserve_default=False,
        ),
    ]
