# Generated by Django 4.2.1 on 2023-05-16 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0025_remove_temporaryaccess_temporary_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporaryaccess',
            name='email',
        ),
    ]
