# Generated by Django 4.2.1 on 2023-05-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0027_alter_payboxsuccesspay_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payboxsuccesspay',
            name='signature',
            field=models.CharField(max_length=255, unique=True, verbose_name='Подпись продукта'),
        ),
    ]
