# Generated by Django 4.2.1 on 2023-05-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0028_alter_payboxsuccesspay_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payboxsuccesspay',
            name='description',
            field=models.CharField(max_length=1000, verbose_name='Описание к оплате'),
        ),
    ]
