# Generated by Django 4.2.1 on 2023-07-28 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0030_promocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='date_of',
            field=models.DateField(default=datetime.datetime(2023, 7, 28, 9, 14, 50, 719713, tzinfo=datetime.timezone.utc), verbose_name='Дата действия промокода'),
        ),
    ]
