# Generated by Django 4.2.1 on 2023-07-28 09:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0031_alter_promocode_date_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='date_of',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата действия промокода'),
        ),
    ]
