# Generated by Django 4.2.1 on 2023-07-28 10:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0032_alter_promocode_date_of'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тема вебинара')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Вводите время по часовому поясу Бишкека', verbose_name='Дата начала')),
                ('promo_code', models.ForeignKey(help_text='Только на латыни', on_delete=django.db.models.deletion.CASCADE, to='payment_app.promocode', verbose_name='Промокод')),
            ],
            options={
                'verbose_name': 'Вебинар',
                'verbose_name_plural': 'Вебинары',
            },
        ),
    ]
