# Generated by Django 4.2.1 on 2023-07-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0033_webinar'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='group_url',
            field=models.URLField(default=3, max_length=255, verbose_name='Ссылка на группу'),
            preserve_default=False,
        ),
    ]
