# Generated by Django 4.2.1 on 2023-07-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0034_webinar_group_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='text',
            field=models.TextField(default=3, verbose_name='Текст приветствия'),
            preserve_default=False,
        ),
    ]
