# Generated by Django 4.2.1 on 2023-08-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0035_webinar_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAdmin',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Телеграм ID')),
            ],
            options={
                'verbose_name': 'Администратор Telegram',
                'verbose_name_plural': 'Администраторы Telegram',
            },
        ),
        migrations.AlterField(
            model_name='webinar',
            name='text',
            field=models.TextField(verbose_name='Текст напоминания'),
        ),
    ]
