# Generated by Django 4.2.1 on 2023-08-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0036_telegramadmin_alter_webinar_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramadmin',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Телеграм ID'),
        ),
    ]
