# Generated by Django 4.2.1 on 2023-08-02 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0037_alter_telegramadmin_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramAdmin',
        ),
    ]
