# Generated by Django 4.2.1 on 2023-08-06 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0038_delete_telegramadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='new_price',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='old_price',
        ),
        migrations.AddField(
            model_name='tariff',
            name='price',
            field=models.IntegerField(default=3, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
