# Generated by Django 4.2.1 on 2023-08-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0040_remove_course_temporary_lms_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='choose_text',
            field=models.TextField(default='ваш ответ записан. Вебинар начнется в {}', help_text='Обязательно оставьте {} для вставки имени пользователя, наример: Привет {}!', verbose_name='Текст после выбора города'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='welcome_text',
            field=models.TextField(default='{} как здорово что ты с нами!', help_text='Обязательно оставьте {} для вставки имени пользователя, наример: Привет {}!', verbose_name='Текст приветствия'),
        ),
    ]
