# Generated by Django 4.2.1 on 2023-08-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0041_webinar_choose_text_webinar_welcome_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='image',
            field=models.ImageField(default=3, help_text='формат обязательно jpeg, png', upload_to='webinar', verbose_name='Изображение для рассылки'),
            preserve_default=False,
        ),
    ]
